name: CMake

on: [push, pull_request]

env:
  GENERATOR: "Unix Makefiles"
  CMAKE_BUILD_TYPE: "Release"
  CCACHE_COMPRESS: 1
  #CCACHE_DIR=: $HOME/.ccache

jobs:
  build:
    name: ${{ matrix.os }}-${{matrix.config.cc}}-${{matrix.qt}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        qt: ["qt5", "qt4"]
        shiboken: ["2"]
        config:
        - {
            cc: "gcc-10", cxx: "g++-10",
            cmake_flags: "-DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_FEM_NETGEN=ON"
          }
        - {
            cc: "clang-10", cxx: "clang++-10",
            cmake_flags: "-DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_FEM_NETGEN=ON"
          }
        - {
            cc: "gcc", cxx: "g++",
            cmake_flags: "-DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_FEM_NETGEN=ON"
          }
        exclude:
        # excludes node 4 on macOS
        - os: ubuntu-20.04
          qt: "qt4"
        include:
        - os: ubuntu-16.04
          qt: "qt5"
          shiboken: ""
          config:
            {
              cc: "gcc", cxx: "g++",
              cmake_flags: "-DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_FEM_NETGEN=ON"
            }
        - os: ubuntu-16.04
          qt: "qt4"
          shiboken: ""
          config:
            {
              cc: "gcc", cxx: "g++",
              cmake_flags: "-DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_FEM_NETGEN=ON"
            }

    steps:
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash
      
    - name: Generate Matrix unique name
      id: matrix-name
      if: runner.os == 'Linux'
      run: |
        echo "::set-output name=concat::${{ matrix.os }}-${{matrix.config.cc}}-${{matrix.qt}}"
        qt_number=$(echo ${{ matrix.qt }} | cut -c3-3)
        echo "::set-output name=qt_number::$qt_number"

    - name: Change Apt Cache permissions
      if: runner.os == 'Linux'
      run: |
        sudo chown -R $(whoami):$(id -ng) /var/cache/apt/archives

    - name: Cache Apt (Linux)
      if: runner.os == 'Linux'
      uses: pat-s/always-upload-cache@v2.1.3
      with:
        path: /var/cache/apt/archives/*.deb
        key: ${{  steps.matrix-name.outputs.concat }}-cache-apt-${{ steps.get-date.outputs.date }}-${{ github.run_number }}
        restore-keys: |
          ${{  steps.matrix-name.outputs.concat }}-cache-apt-${{ steps.get-date.outputs.date }}-
          ${{  steps.matrix-name.outputs.concat }}-cache-apt-

    - name: Cache ccache (Linux)
      uses: pat-s/always-upload-cache@v2.1.3
      if: runner.os == 'Linux' 
      with:
        path: ~/.ccache
        key: ${{  steps.matrix-name.outputs.concat }}-cache-ccache-${{ steps.get-date.outputs.date }}-${{ github.run_number }}
        restore-keys: |
          ${{  steps.matrix-name.outputs.concat }}-cache-ccache-${{ steps.get-date.outputs.date }}-
          ${{  steps.matrix-name.outputs.concat }}-cache-ccache-

    - name: Set Environment Variables (Linux)
      if: runner.os == 'Linux' 
      run: |
        echo "INSTALLED_APP_PATH=/usr/local/bin/FreeCAD" >> $GITHUB_ENV
        #https://forum.freecadweb.org/viewtopic.php?f=3&t=40677
        echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/netgen/:$LD_LIRBARY_PATH" >> $GITHUB_ENV
        ([ "${{matrix.qt}}" == "qt5" ] && echo 'BUILD_QT5=ON' || echo 'BUILD_QT5=OFF') >> $GITHUB_ENV

    - name: Install compiler ${{matrix.config.cc}} (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install ${{matrix.config.cc}}  ${{matrix.config.cxx}}

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-add-repository -y ppa:freecad-maintainers/freecad-daily 
        sudo apt-get update -qq
        # Build deps
        sudo apt-get install -y --no-install-recommends         \
                               python3-dev                      \
                               python3-matplotlib               \
                               libboost-dev                     \
                               libboost-filesystem-dev          \
                               libboost-program-options-dev     \
                               libboost-python-dev              \
                               libboost-regex-dev               \
                               libboost-system-dev              \
                               libboost-thread-dev              \
                               libxerces-c-dev                  \
                               libocct-data-exchange-dev        \
                               libocct-ocaf-dev                 \
                               libocct-visualization-dev        \
                               libmedc-dev                      \
                               pybind11-dev                     \
                               swig                             \
                               libcoin-dev                      \
                               doxygen                          \
                               graphviz                         \
                               libnglib-dev                     \
                               netgen                           \
                               netgen-headers                   \
                               libmetis-dev                     \
                               libspnav-dev                     \
                               libshiboken${{matrix.shiboken}}-dev  \
                               ccache

        if [[ $(lsb_release -rs) == "16.04" ]]; then 
          sudo apt-get install -y \
            libvtk6-dev
        else
          sudo apt-get install -y \
            libvtk7-dev
        fi

        # Runtime deps
        sudo apt-get install -y --no-install-recommends freecad-daily-python3 python3-pivy python3-ply

        ## Use newer Eigen to suppress warnings
        ## https://github.com/FreeCAD/FreeCAD/pull/3485
        #wget http://mirrors.kernel.org/ubuntu/pool/universe/e/eigen3/libeigen3-dev_3.3.7-2_all.deb
        #sudo dpkg -i libeigen3-dev_3.3.7-2_all.deb
        ##export DISPLAY=:99.0
        ##sh -e /etc/init.d/xvfb start

        #export INSTALLED_APP_PATH="/usr/local/bin/FreeCAD"
        #echo "INSTALLED_APP_PATH=/usr/local/bin/FreeCAD" >> $GITHUB_ENV

        #export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/netgen/:$LD_LIRBARY_PATH
        #echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/netgen/:$LD_LIRBARY_PATH" >> $GITHUB_ENV
        #echo "DISPLAY=:99.0" >> $GITHUB_ENV

    - name: Install QT4 (Linux)
      if: runner.os == 'Linux' && matrix.qt == 'qt4'
      run: |
        sudo apt-get install -y --no-install-recommends          \
        qt4-qmake                        \
        libqt4-opengl-dev                \
        libqtwebkit-dev                  \
        libpyside-dev                    \
        pyside-tools                     \
        python3-pyside                   \
        pyside-tools                     \
        python3-pyqt4

    - name: Install QT5 (Linux)
      if: matrix.qt == 'qt5' && matrix.os != 'ubuntu-16.04'
      run: |
        sudo apt-get install -y --no-install-recommends          \
        qt5-qmake                        \
        libqt5xmlpatterns5-dev           \
        libqt5svg5-dev                   \
        libqt5opengl5-dev                \
        qttools5-dev                     \
        qtwebengine5-dev                 \
        qtbase5-dev                      \
        pyside2-tools                    \
        python3-pyside2.qtopengl         \
        pyqt5-dev-tools

    - name: Install QT5 - Ubuntu 16.04 (Linux)
      if: matrix.qt == 'qt5' && matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt-get install -y --no-install-recommends          \
        qt5-qmake                        \
        libqt5xmlpatterns5-dev           \
        libqt5svg5-dev                   \
        libqt5opengl5-dev                \
        qttools5-dev                     \
        libqt5webkit5-dev                \
        qtbase5-dev                      \
        pyside-tools                     \
        python3-pyside                   \
        pyqt5-dev-tools

    - name: Checkout 
      uses: actions/checkout@v2
    - name: Configure
      run: |
        mkdir build && cd build 
        CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} \
        cmake -Wno-dev -G"${GENERATOR}" \
        ${{matrix.config.cmake_flags}} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DBUILD_QT5=${BUILD_QT5} ../
    - name: Install and Test (Linux)
      if: runner.os == 'Linux'
      run: |
        export N=$(($(grep -c ^processor /proc/cpuinfo) + 1))
        cd build
        # Stop compiling (GCC) after 2 hrs 50 min (3 hrs limit).
        # Preserves created ccache for the next build job.
        # if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo timeout -k 175m 170m make -j2 install || true; fi
        # if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo gtimeout -s KILL  make -j2 install; fi
        #cat $HOME/.ccache/ccache.conf
        ccache -z -s -M 400M
        df -h
        #if [ "${TRAVIS_OS_NAME}" == "osx" ]; then export PATH="/usr/local/opt/ccacche/libexec:$PATH"; sudo gtimeout -s KILL 7200 make -j2; [ $? == 124 ] && { ccache -s; return 0; }  fi 
        #if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo timeout -k 175m 170m make -j2 install || true; fi
        #sudo make -j${N} install
        #make -j${N} Part
        echo "::group::Run cmake"
        sudo cmake --build ./ --target install -j ${N}
        echo "::endgroup::"
        echo "::group::ccache statistics"
        ccache -s
        echo "::endgroup::"
        #make clean
        #cmake --build ./ --target FreeCADBase  -j ${N}
        #ccache -s
        echo "FreeCAD installed bin:" ${INSTALLED_APP_PATH}
        echo "::group::Run tests"
        ${INSTALLED_APP_PATH} --console --run-test 0
        echo "::endgroup::"
        echo "::warning::Tests Completed"
        xvfb-run --auto-servernum ${INSTALLED_APP_PATH} --log-file /tmp/FreeCAD_installed.log &
        sleep 10 && pkill FreeCAD
        cat /tmp/FreeCAD_installed.log
        #grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )
